/**
 * Prints every registered API route (method + path) by walking the Express router tree.
 *   npx tsx scripts/list-routes.ts > docs/ROUTES.md
 */
process.env.DATABASE_URL ??= 'postgres://localhost/unused';
process.env.JWT_SECRET ??= 'x'.repeat(40);
process.env.AUTH_PROVIDER ??= 'local';
process.env.STORAGE_PROVIDER ??= 'local';
process.env.LOG_LEVEL = 'silent';
const { createApp } = await import('../src/app.js');

interface Layer {
  route?: { path: string; methods: Record<string, boolean> };
  name: string;
  handle: { stack?: Layer[] };
  regexp: RegExp;
  keys: { name: string }[];
}

/** Recovers the mount path from Express 4's compiled layer regexp. */
function prefixOf(layer: Layer): string {
  let src = layer.regexp.source;
  if (src === '^\\/?$' || src === '^\\/?(?=\\/|$)') return '';
  src = src.replace(/^\^/, '').replace(/\\\/\?\(\?=\\\/\|\$\)$/, '').replace(/\(\?=\\\/\|\$\)$/, '');
  let i = 0;
  src = src.replace(/\(\?:\(\[\^\\\/\]\+\?\)\)/g, () => `:${layer.keys[i++]?.name ?? 'param'}`);
  return src.replace(/\\\//g, '/').replace(/\/\?$/, '');
}

const rows: string[] = [];
function walk(stack: Layer[], base: string) {
  for (const l of stack) {
    if (l.route) {
      for (const m of Object.keys(l.route.methods)) rows.push(`${m.toUpperCase().padEnd(7)} ${base}${l.route.path === '/' ? '' : l.route.path}`);
    } else if (l.name === 'router' && l.handle.stack) walk(l.handle.stack, base + prefixOf(l));
  }
}

const app = createApp() as unknown as { _router: { stack: Layer[] } };
walk(app._router.stack, '');
const unique = [...new Set(rows.map((r) => r.split('(?:/([^/]+?))').join('/:id')))].filter((r) => r.includes('/api/v1') || r.includes('/health'));
console.log('# SPORTX API routes (generated)\n\nGenerated by `npx tsx scripts/list-routes.ts`. See API.md for request/response details.\n\n```');
console.log(unique.join('\n'));
console.log('```');
process.exit(0);

export {};
